### ISSUE TITLE
instant crash rendering with nvidia gpus

### ISSUE THREAD

**Issue by nospitters** [GPUOpen-LibrariesAndSDKs/RadeonProRenderMayaPlugin#375] opened 2023-03-29 08:20 UTC
hi,

installed latest release (3.4.1) for maya and when rendering with nvidia gpus (2x rtx 2080ti, studio driver 528.xx) i get instant crash...
rendering on cpu only is fine...
in the docs it says, that rendering on nvidia gpus is supported...
had once a previous version installed (i think it was 3.3.x) and there gpu rendering was ok...
does someone also has this experience?

**Comment by bsavery** [comment] 2023-03-29 22:10
There was a bug caused by the nvidia drivers.  We are working around it, but to be clear this came from their driver side.  We can't control that.

**Comment by nospitters** [comment] 2023-03-30 06:26
thx for the info. i see...
so what driver version do you reccommend prior 528.xx? one version below or much older...

**Comment by DavidSpeicher** [comment] 2023-06-12 08:29
issue should be fixed

**Closed** 2023-06-12 08:33 UTC
